# Installing Necessary Packages on Your Computer {.sec-installation}

There are a few programs that we will need to install: Homebrew, node, ispell, and gnu-tar.

Homebrew is necessary as MacOS's package manager. This will allow you to install various programs via the command line. Node.js, ispell, and gnu-tar are all dependencies that are needed in order to integrate with Copilot.

To do so, please open your Terminal. (If you don't know where this is: Finder > Applications > Utilities > Terminal). 

* Now type: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
* Press enter. Follow the instructions. It will likely give you a message to copy two lines of code. Copy and paste the first and press enter. When that is done, copy and paste the second and press enter. 
  * The first: (echo; echo ‘eval “$(/opt/homebrew/bin/brew shellenv)“’) >> /Users/<yourusername>/.zprofile
  * The second: eval “$(/opt/homebrew/bin/brew shellenv)”

Once Homebrew is installed, we can now install the three dependencies in your terminal. One by one, please copy and paste the following lines and execute separately (by pressing return after each).

* brew install gnu-tar
* brew install node
* brew install ispell

You should now be done!

If you run into any problems installing these, please refer to documentation online for [Homebrew](https://brew.sh/), [gnu-tar](https://formulae.brew.sh/formula/gnu-tar), [node.js](https://nodejs.org/en/download/package-manager/), and [ispell](https://formulae.brew.sh/formula/ispell).
